name: Test
on:
  push:
  pull_request:

env:
  dotnetVersion: 10.x.x
  testProjectPath: Idam.EntityFrameworkCore.Timestamps.Tests

permissions:
  contents: read

jobs:
  test:
    name: "Test the package before publish"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET ${{ env.dotnetVersion }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.dotnetVersion }}

      - name: Cache .NET Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('global.json', 'Directory.Build.props', 'Directory.Packages.props', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore `${{ env.testProjectPath }}` Dependencies 
        run: dotnet restore ${{ env.testProjectPath }}

      - name: Build `${{ env.testProjectPath }}`
        run: dotnet build ${{ env.testProjectPath }} --configuration Release --no-restore

      - name: Test 
        run: dotnet test ${{ env.testProjectPath }} --no-restore --verbosity normal
